[build]
  # Sem build steps: apenas publica a raiz
  publish = "."

[dev]
  # Para testar localmente com `netlify dev`
  framework = "#custom"

# Cache longo e CORS para seu JS
[[headers]]
  for = "/xflow.js"
  [headers.values]
    Cache-Control                = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin  = "*"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/xflow-lite.js"
  [headers.values]
    Cache-Control                = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin  = "*"
    Cross-Origin-Resource-Policy = "cross-origin"
