[build]
  # Sem build steps: apenas publica a raiz
  publish = "."

[dev]
  # Para testar localmente com `netlify dev`
  framework = "#custom"

# Cache longo para seu JS
# netlify.toml
[[headers]]
  for = "/xflow.js"
  [headers.values]
    Cache-Control                = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin  = "*"                    # libera para qualquer origem
    Cross-Origin-Resource-Policy = "cross-origin"         # indica que o recurso pode ser carregado cross-origin

