[build]
  # Sem build steps: apenas publica a raiz
  publish = "."

[dev]
  # Para testar localmente com `netlify dev`
  framework = "#custom"

# Cache longo para seu JS
[[headers]]
  for = "/xflow.js"
  [headers.values]
    # cache longo em CDN
    Cache-Control = "public, max-age=31536000, immutable"
    # libera para QUALQUER origem
    Access-Control-Allow-Origin = "*"
    # indica explicitamente que este recurso pode ser carregado cross-origin
    Cross-Origin-Resource-Policy = "cross-origin"
